version: "1"
services:
  - type: web
    name: grievance-ai-backend
    runtime: python
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 2 -b 0.0.0.0:10000 backend.server:app"
    envVars:
      - key: PORT
        value: "10000"
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: HF_API_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false